### ISSUE TITLE
opencv 版本

### ISSUE THREAD

**Issue by OutBreak-hui** [hpc203/virtual_try_on_use_deep_learning#1]
请问大佬用的opencv的版本号是多少

**Comment by GerogeLiu** [comment]
```
python==3.8.0
certifi==2021.10.8
numpy==1.22.1
opencv-python==4.5.1.48
wincertstore==0.2
```
测试可以运行

**Comment by snowjake** [comment]
> wincertstore

大佬您好 为啥我跑完结果是黑屏呢？  你那边可以吗

**Comment by snowjake** [comment]
已解决 乘以255即可

**Comment by sliontc** [comment]
我无法运行成功，麻烦看看什么原因

[ERROR:0@5.974] global D:\a\opencv-python\opencv-python\opencv\modules\dnn\src\dnn.cpp (3875) cv::dnn::dnn4_v20211220::Net::Impl::getLayerShapesRecursively OPENCV/DNN: [Permute]:(Mean/nhwc): getMemoryShapes() throws exception. inputs=1 outputs=0/1 blobs=0
[ERROR:0@5.988] global D:\a\opencv-python\opencv-python\opencv\modules\dnn\src\dnn.cpp (3878) cv::dnn::dnn4_v20211220::Net::Impl::getLayerShapesRecursively     input[0] = [ 1 2 20 384 384 ]
[ERROR:0@6.009] global D:\a\opencv-python\opencv-python\opencv\modules\dnn\src\dnn.cpp (3888) cv::dnn::dnn4_v20211220::Net::Impl::getLayerShapesRecursively Exception message: OpenCV(4.5.5) D:\a\opencv-python\opencv-python\opencv\modules\dnn\src\layers\permute_layer.cpp:140: error: (-215:Assertion failed) (int)_numAxes == inputs[0].size() in function 'cv::dnn::PermuteLayerImpl::getMemoryShapes'

Traceback (most recent call last):
  File "main.py", line 431, in <module>
    segm_image = parse_human(person_img, args.segmentation_model)
  File "C:\Users\Administrator\Downloads\virtual_try_on_use_deep_learning-main\human_parsing.py", line 105, in parse_human
    output = run_net(input, model_path, backend, target)
  File "C:\Users\Administrator\Downloads\virtual_try_on_use_deep_learning-main\human_parsing.py", line 28, in run_net
    out = net.forward()
cv2.error: OpenCV(4.5.5) D:\a\opencv-python\opencv-python\opencv\modules\dnn\src\layers\permute_layer.cpp:140: error: (-215:Assertion failed) (int)_numAxes == inputs[0].size() in function 'cv::dnn::PermuteLayerImpl::getMemoryShapes'

**Comment by fun-code-ai** [comment]
> > wincertstore
> 
> 大佬您好 为啥我跑完结果是黑屏呢？ 你那边可以吗

大佬您好，请问下这个代码应该怎么跑？

**Comment by fun-code-ai** [comment]
> 我无法运行成功，麻烦看看什么原因
> 
> [ERROR:0@5.974] global D:\a\opencv-python\opencv-python\opencv\modules\dnn\src\dnn.cpp (3875) cv::dnn::dnn4_v20211220::Net::Impl::getLayerShapesRecursively OPENCV/DNN: [Permute]:(Mean/nhwc): getMemoryShapes() throws exception. inputs=1 outputs=0/1 blobs=0 [ERROR:0@5.988] global D:\a\opencv-python\opencv-python\opencv\modules\dnn\src\dnn.cpp (3878) cv::dnn::dnn4_v20211220::Net::Impl::getLayerShapesRecursively input[0] = [ 1 2 20 384 384 ] [ERROR:0@6.009] global D:\a\opencv-python\opencv-python\opencv\modules\dnn\src\dnn.cpp (3888) cv::dnn::dnn4_v20211220::Net::Impl::getLayerShapesRecursively Exception message: OpenCV(4.5.5) D:\a\opencv-python\opencv-python\opencv\modules\dnn\src\layers\permute_layer.cpp:140: error: (-215:Assertion failed) (int)_numAxes == inputs[0].size() in function 'cv::dnn::PermuteLayerImpl::getMemoryShapes'
> 
> Traceback (most recent call last): File "main.py", line 431, in segm_image = parse_human(person_img, args.segmentation_model) File "C:\Users\Administrator\Downloads\virtual_try_on_use_deep_learning-main\human_parsing.py", line 105, in parse_human output = run_net(input, model_path, backend, target) File "C:\Users\Administrator\Downloads\virtual_try_on_use_deep_learning-main\human_parsing.py", line 28, in run_net out = net.forward() cv2.error: OpenCV(4.5.5) D:\a\opencv-python\opencv-python\opencv\modules\dnn\src\layers\permute_layer.cpp:140: error: (-215:Assertion failed) (int)_numAxes == inputs[0].size() in function 'cv::dnn::PermuteLayerImpl::getMemoryShapes'

请问下解决了吗，我也遇到这个问题

**Comment by snowjake** [comment]
没遇到这个 我直接就能跑 就是黑屏 乘以255就好了

**Comment by GerogeLiu** [comment]
> 
请确认下opencv的版本 是如下版本吗？
opencv-python==4.5.1.48

**Comment by fun-code-ai** [comment]
> 没遇到这个 我直接就能跑 就是黑屏 乘以255就好了

感谢，已经解决了

**Comment by fun-code-ai** [comment]
> > 
> 
> 请确认下opencv的版本 是如下版本吗？ opencv-python==4.5.1.48
感谢，是版本的问题

**Comment by snowjake** [comment]
certifi       2021.10.8
numpy         1.22.2
opencv-python 4.5.1.48
pip           21.2.2
pyasn1        0.4.8
pyDes         2.0.1
rsa           4.7.2
setuptools    58.0.4
wheel         0.37.1
wincertstore  0.2
